version: 0.0
os: linux
files:
- source: /
  destination: /var/www/html/EDUC-DOG
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/build_socket.sh
      timeout: 1200
      runas: ubuntu