version: 0.0
os: linux
files:
- source: /
  destination: /var/www/html/EDUC-DOG
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 1600
      runas: ubuntu
  AfterInstall:
    - location: scripts/build_socket.sh
      timeout: 1600
      runas: ubuntu